max_samples_per_estimator: 5000
model: TabPFN Ensemble (v2)
n_estimators: 5
test_metrics:
  AUC: 0.992657533981458
  F1: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    mJJT/t8b5T8=
  Precision: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    Wj2y0E0m5j8=
  Recall: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    w41iD1wp5D8=
  auPRC: 0.7662260850422091
validation_metrics:
  AUC: 0.995775539728148
  F1: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    pI1d9Whj5z8=
  Precision: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    JHefydIt5z8=
  Recall: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    llkgKPmZ5z8=
  auPRC: 0.855607380438224
