gene_level:
  test:
    AUC: 0.9906747800308018
    F1: !!python/object/apply:numpy._core.multiarray.scalar
    - &id001 !!python/object/apply:numpy.dtype
      args:
      - f8
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - !!binary |
      qFmd35wI5z8=
    Precision: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      YOIZnfob6z8=
    Recall: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      KqQttvcF5D8=
    auPRC: 0.7662112000130341
    threshold: &id002 !!python/object/apply:numpy._core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - f4
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - !!binary |
      ouJ8Pw==
  train:
    AUC: 0.9989875336360957
    F1: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      o3EeatW56T8=
    Precision: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      JhCADUkR6z8=
    Recall: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      zr6QFdKC6D8=
    auPRC: 0.8853884341785873
    threshold: *id002
  val:
    AUC: 0.9885742310836976
    F1: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      zrW35hhE6D8=
    Precision: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      8RIVLbt56T8=
    Recall: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      EJGxKogq5z8=
    auPRC: 0.811309649174486
    threshold: *id002
model: XGB11_original
sample_level:
  test:
    AUC: 0.9375
    Accuracy: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      velNb3rT6z8=
    F1: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      Whm+EQUm7T8=
    Precision: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      q6qqqqqq7j8=
    Recall: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      ln0OqQnG6z8=
    auPRC: 0.9822034972575426
    positive_samples: 53
    predicted_positive: 48
    total_samples: 69
  train:
    AUC: 0.9529499626587006
    Accuracy: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      fcTQrTj86z8=
    F1: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      SOF6FK5H7T8=
    Precision: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      rn7QUYEv7j8=
    Recall: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      oukO9ltt7D8=
    auPRC: 0.9855816198531707
    positive_samples: 206
    predicted_positive: 194
    total_samples: 271
  val:
    AUC: 0.8701298701298702
    Accuracy: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      hixkIQtZ6D8=
    F1: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      rx2Yawfm6j8=
    Precision: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      S0tLS0tL6z8=
    Recall: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      O6iDOqiD6j8=
    auPRC: 0.9613265593389073
    positive_samples: 35
    predicted_positive: 34
    total_samples: 46
