gene_level:
  test:
    AUC: 0.9929957831386829
    F1: !!python/object/apply:numpy._core.multiarray.scalar
    - &id001 !!python/object/apply:numpy.dtype
      args:
      - f8
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - !!binary |
      tDXalYNq5z8=
    Precision: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      uoiq4iU+5j8=
    Recall: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      pkCeUFW46D8=
    auPRC: 0.7738926386930107
    threshold: &id002 !!python/object/apply:numpy._core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - f4
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - !!binary |
      gzZ1Pw==
  train:
    AUC: 0.9993600647916168
    F1: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      BZaPS6s46T8=
    Precision: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      GBtKlxQu5j8=
    Recall: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      yxQQUrY67T8=
    auPRC: 0.9110829563460022
    threshold: *id002
  val:
    AUC: 0.9929384372157843
    F1: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      UVI/zhRL5z8=
    Precision: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      Mc1d8Fdx5D8=
    Recall: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      u9dWyU0R6z8=
    auPRC: 0.8058006538876149
    threshold: *id002
model: XGB11_optimized
sample_level:
  test:
    AUC: 0.9469339622641509
    Accuracy: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      xc8o8TNK7D8=
    F1: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      6JCaYLyV7T8=
    Precision: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      6JCaYLyV7T8=
    Recall: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      6JCaYLyV7T8=
    auPRC: 0.9849138363688872
    positive_samples: 53
    predicted_positive: 53
    total_samples: 69
  train:
    AUC: 0.9558625840179239
    Accuracy: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      zFg+YuhW7D8=
    F1: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      y7lrAqSn7T8=
    Precision: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      55xzzjnn7D8=
    Recall: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      zCI+gVRy7j8=
    auPRC: 0.9867564083484182
    positive_samples: 206
    predicted_positive: 217
    total_samples: 271
  val:
    AUC: 0.9246753246753247
    Accuracy: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      velNb3rT6z8=
    F1: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      VlVVVVVV7T8=
    Precision: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      pshn3WCK7D8=
    Recall: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      vuIrvuIr7j8=
    auPRC: 0.9777851945232551
    positive_samples: 35
    predicted_positive: 37
    total_samples: 46
